version: '3'
services:
  jekyll:
    # image: dothtm/alpine_jekyll_grunt:latest
    build: 
      context: ./docker
      dockerfile: jekyll-grunt.dockerfile
    volumes:
      - "./source:/app/source"
    ports:
      - "4000:4000"
    entrypoint: "/jekyll_entry.sh"

  apache:
    image: httpd
    volumes:
      - "./source/_site:/usr/local/apache2/htdocs"
    ports:
      - "80:80"
      - "443:443"